
SELECT 
     COUNT(*)AS TOTAL 
FROM NETFLIX;

SELECT 
     DISTINCT type
FROM NETFLIX;

-- COUNT THE NUMBERS OF MOVIES VS TV SHOWS

SELECT 
   type
   ,COUNT(*)
FROM NETFLIX
GROUP BY 1;

-- FIND THE MOST COMMON RATING FOR MOVIES AND TV SHOW

SELECT 
 type
,rating FROM
(
SELECT type,rating,COUNT(*),
RANK()OVER(PARTITION BY type ORDER BY COUNT(*)DESC)AS ranking
FROM NETFLIX
GROUP BY 1,2
)AS N1
WHERE ranking=1;

-- LIST ALL MOVIES RELEASED IN A SPECIFIC YEAR(e.g..2020)

select * from NETFLIX
where type='Movie'
and release_year=2020;

-- FIND THE TOP 5 COUNTRIES WITH THE MOST CONTENT ON NETFLIX

SELECT
UNNEST(STRING_TO_ARRAY(country,','))as COUNTRY
,count(show_id)
from NETFLIX
GROUP BY 1
ORDER BY 2 DESC LIMIT 5;

IDENTIFY THE LONGEST MOVIES

SELECT * FROM NETFLIX
WHERE type='Movie'
    AND
	duration=(SELECT MAX(duration)FROM NETFLIX)

-- FIND CONTENT ADDED IN THE LAST 5 YEARS

SELECT*FROM NETFLIX
WHERE
     TO_DATE(date_added,'Month DD,YYYY')>= CURRENT_DATE-INTERVAL'5 years'

-- FIND ALL THE MOVIES/TV SHOWS BY DIRECTION 'RAJIV CHILAKA'

SELECT * FROM NETFLIX
  WHERE director LIKE'%Rajiv Chilaka%';

-- LIST ALL TV SHOWS WITH MORE THAN 5 SEASONS

SELECT*FROM NETFLIX
WHERE
    type='TV Show'
	AND 
	SPLIT_PART(duration,' ',1)::numeric>5 

-- COUNT THE NUMBER OF CONTENT ITEMS IN EACH GENRE

SELECT
     UNNEST(STRING_TO_ARRAY(listed_in,','))AS GENRE ,
	 COUNT(show_id) AS TOTAL_CONTENT
FROM NETFLIX
GROUP BY 1;

-- LIST ALL MOVIES THAT ARE DOCUMENTARIES

SELECT*FROM NETFLIX
WHERE 
    listed_in like '%Documentaries%'
	

-- LIST ALL CONTENT WITHOUT A DIRECTOR

SELECT*FROM NETFLIX
WHERE director IS NULL;

-- FIND HOW MANY MOVIES ACTOR'Salman Khan' APPEARED IN LAST 10 YEARS

SELECT * FROM NETFLIX
WHERE casts ILIKE '%salman khan%'
AND
release_year>EXTRACT(YEAR FROM CURRENT_DATE)-10 

-- FIND THE TOP 10 ACTORS WHO HAVE APPEARED IN THE HIGHEST NUMBER OF MOVIES PRODUCED IN INDIA

SELECT 
UNNEST(STRING_TO_ARRAY(casts,','))as actors,
COUNT(*)as total_content
FROM NETFLIX
WHERE country ILIKE '%India'
GROUP BY 1
ORDER BY 2 DESC LIMIT 10;

-- CATEGORIZE THE CONTENT BASED ON THE PRSENCE OF THE KEYWORDS 'KILL' AND 'VIOLENCE' IN THE DESCRIPTION FIELD.
-- LABEL CONTENT CONTAING THESE KEYWORD AS'BAD' AND ALL OTHER CONTENT AS 'GOOD'.COUNT HOW MANY ITEMS FALL INTO EACH CATEGORY
    
WITH new_table
AS(
SELECT*
,CASE
 WHEN description Ilike'%kil%'  OR
  description Ilike'%violence%' THEN 'Bad Content'
 ELSE 'Good Content'
 END Category
FROM NETFLIX
)
SELECT
     Category,
	 COUNT(*)as total_content
FROM new_table
GROUP BY 1;
